spring.datasource.url=jdbc:postgresql://localhost:5432/flowops
spring.datasource.username=isluc
spring.datasource.password=1604
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080